swagger: "2.0"
info:
  description: "Unlearn's Asset API"
  version: "0.1.0"
  title: "Unlearn Kids"
host: "unlearnkids.com"
basePath: "/api/v1"

definitions:
  
  assetID:
    properties:
      id:
        type: string
  
  assetReference:
    properties:
      content:
        type: object
  
  Asset:
    type: "object"
    properties:
      asset_data:
        type: object
      name:
        type: string
      category:
        type: string
      author:
        type: string
      session:
        type: string
      tags:
        type: array
        items:
          type: string
          
    
  Invalid:
    type: "object"
    properties:
      message:
        type: string
        
  EditMessage:
    type: "object"
    properties:
      edited_count:
        type: integer
    
  
  unauthorized:
    properties:
      message:
        type: string

        


  
schemes:
- "https"
- "http"

paths:
  
  /asset/{assetID}:
    get:
      tags:
        - "Asset"
      summary: "Asset detail"
      description: "Send details of an Asset"
      operationId: "assetID"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - name: "assetID"
        in: "path"
        description: "ID of Asset to return"
        required: true
        type: "string"
      responses:
        "200":
          description: "User details"
          schema:
            $ref: '#/definitions/assetReference'
        "401":
          description: "Unauthorized access"
          schema:
            $ref: '#/definitions/unauthorized'
    
    
    delete:
      tags: 
        - "Asset"
      summary: "Delete an Asset"
      description: "Delete Asset based on given id"
      operationId: "deleteAsset"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "assetID"
          in: "path"
          description: "ID of Asset"
          required: true
          type: "string"
        
      responses:
        "202":
          description: "User Deleted"
          schema:
            $ref: '#/definitions/EditMessage'
        "400":
          description: "ID missing"
          schema:
            $ref: '#/definitions/Invalid'
        "401":
          description: "Unauthorized access"
          schema:
            $ref: '#/definitions/unauthorized'
            
    put:
      tags: 
        - "Asset"
      
      summary: "Update an Asset"
      description: "Update Asset based on given id"
      operationId: "updateAsset"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "assetID"
          in: "path"
          description: "ID of Asset to update"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Edit Asset Details"
          schema:
            $ref: '#/definitions/Asset'
        
      responses:
        "202":
          description: "Asset Updated"
          schema:
            $ref: '#/definitions/EditMessage'
        "400":
          description: "id missing"
          schema:
            $ref: '#/definitions/Invalid'
        "401":
          description: "Unauthorized access"
          schema:
            $ref: '#/definitions/unauthorized'
  
  /asset:  
    post:
      tags: 
        - "Asset"
      
      summary: "Add New Asset"
      description: "Add new asset"
      operationId: "addAsset"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Add User Details"
          schema:
            $ref: '#/definitions/Asset'
      responses:
        "201":
          description: "New Asset Created"
          schema:
            $ref: '#/definitions/assetID'
        "400":
          description: "Missing Parameter"
          schema:
            $ref: "#/definitions/Invalid"
        "401":
          description: "Unauthorized access"
          schema:
            $ref: '#/definitions/unauthorized'
        
  